language: java
sudo: false
script: mvn -Dtestng.groups="travis-ci" -Dlogback.configurationFile=dbptk-core/src/test/resources/logback-travis.xml clean verify
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
os:
  - linux
