language: java
sudo: false
addons:
  sonarqube:
    token:
      secure: ccxxJ80A2fo5zKRxu8Rko61b3QIo1z2jqkjqamGO6zPfpwzKcXt5wjYWksJOlV7m3uNNkVV0Z7YeiTQ3nr+XMa5lhgOip1/ZnNI2pbUR9csE+0NTRFBe5e9nho/BUC5j79yrH1A8GTi6nTqZbxUOl9karfpjrCcs3CMojYtN5Dk=
script:
    # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - travis_wait 30 mvn -Dtestng.groups="travis-ci" -Dlogback.configurationFile=logback-travis.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent install $SONARPLUGIN
jdk:
  - oraclejdk7
  - openjdk7
matrix:
  include:
  - jdk: oraclejdk8
    env: SONARPLUGIN=sonar:sonar
os:
- linux
notifications:
  slack:
    secure: M7jJ1dmO1cx//vgzY5UgE650Fe/lm21Dm8WLDXJfz66hmjQihoYCzW19Id/ySgPs/exjEvS1Lvxa4r4t5mgQOe+uPpQOZKEK3IfQ6h7zIv40Rbsa6mY9GaAW4x1Obji5a7HNGD7BQiolYDX1jmtBxOcSetesvL5iX1Bru0E/R78=
branches:
  except:
    - code-analysis
